tasks: 
  - name: install v2ray 
    init: |
      sudo wget https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
      sudo bash install-release.sh
      echo "${VRAY_CONFIG}" | sudo tee /tmp/vray_config.json > /dev/null 
      sudo chmod -R o=rw /var/log/v2ray/
    command: sudo v2ray run -config /tmp/vray_config.json

# write package to file tcpdump -w $(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name).cap
  - name: install tcpdump
    init: |
      gp ports await ${VRAY_PORT}
      sudo apt install tcpdump -y
    command: sudo tcpdump -i ceth0 tcp port ${VRAY_PORT} or port 443 
    openMode: split-right
      
  - name: watch port
    init: gp ports await ${VRAY_PORT}
    command: sudo watch -n 1 -d 'ss -a | grep ${VRAY_PORT}'
    openMode: tab-after
