tasks:
  - init: |
      sudo wget https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
      sudo bash install-release.sh
    command: v2ray run -config release/config/vpoint_vmess_freedom.json
ports:
  - name: tcp stream
    description: v2ray inbound tcp steam
    port: 10086
    onOpen: notify
    visibility: public
