tasks:
  - init: |
      sudo wget https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
      sudo bash install-release.sh
      echo "${VRAY_HTTP}" | sudo tee /tmp/vray_config.json > /dev/null 
      sudo chmod -R o+rw /var/log/v2ray/
    command: sudo v2ray run -config /tmp/vray_config.json
ports:
  - name: tcp stream
    description: v2ray inbound tcp steam
    port: 10087
    onOpen: notify
    visibility: public
